version: "3.9"
services:
  nextjs-dashboard:
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ../../:/usr/src/app/
      - ./app-startup.sh:/usr/src/app/app-startup.sh
    networks:
      - default
    env_file:
      - .env
  nextjs-db:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - ../../db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextjs-dashboard
      POSTGRES_USER: nextjs-dashboard
      POSTGRES_PASSWORD: nextjs-dashboard
    networks: 
      - default

  #docker compose logs nextjs-dashboard