version: "3.9"
services:
  nextjs-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../.:/usr/src/app
    environment:
      TZ: Europe/Berlin
    networks:
      - default
    command: /usr/src/app/startup-script.sh
  nextjs-db:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - ../../db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextjs-dashboard
      POSTGRES_USER: nextjs-dashboard
      POSTGRES_PASSWORD: nextjs-dashboard
      TZ: Europe/Berlin
    networks: 
      - default