version: "3.9"
services:
  nextjs-dashboard:
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ../../:/usr/src/app/
      - ./app-startup.sh:/usr/src/app/app-startup.sh
    networks:
      - default
    env_file:
      - .env
  nextjs-db:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - ../../db:/var/lib/postgresql/data
    env_file:
      - .env
    networks: 
      - default